### PR TITLE
Rename `master` to `main`

### PR DESCRIPTION
**Pull request by sloede**
@ranocha A review would be great, but don't merge it yet - I still need to figure out if merging or renaming comes first.

### CODE REVIEW

**Comment by sloede** [comment]
FWIW, I think we should **first rename** `master` to `main`, **then merge** this PR. I think the renaming will not trigger any CI action, but the PR merge will, so it will be a first test if everything went smoothly and it will also make sure that we (hopefully) have all working links again.

**Comment by ranocha** [comment]
We should also consider closing and re-opening this PR after renaming `master` to `main` to trigger some CI.

**Review by ranocha — APPROVED** [review]

**Comment by ranocha** [comment]
Didn't you want to wait before merging this, @sloede ?

**Comment by sloede** [comment]
Sorry, I misread your statement and then merged too hastily. Also, I am not sure if re-opening this PR would've done anything, since CI is triggered from the scripts in `main`, not from the PR, isn't it? But it's too late right now anyways... I hope the CI runs through.

**Comment by ranocha** [comment]
If you close an re-open a PR, CI is triggered again (in the PR).

**Comment by sloede** [comment]
Yes, but isn't the PR CI controlled by the CI of the `main` branch? I might be mistaken though. I just thought it was a security measure, such that people could not just create PRs with arbitrary commands in the CI, but I might be wrong.

**Pull request merged**
